<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introducción al diseño y análisis estadístico de experimentos usando R</title>
  <meta name="description" content="Material complementario para el dictado del curso <em>Diseño de Experimentos</em> de la Maestría de Cultivos Intensivos de la FCA-UNL">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Introducción al diseño y análisis estadístico de experimentos usando R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/choose_OS.png" />
  <meta property="og:description" content="Material complementario para el dictado del curso <em>Diseño de Experimentos</em> de la Maestría de Cultivos Intensivos de la FCA-UNL" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introducción al diseño y análisis estadístico de experimentos usando R" />
  
  <meta name="twitter:description" content="Material complementario para el dictado del curso <em>Diseño de Experimentos</em> de la Maestría de Cultivos Intensivos de la FCA-UNL" />
  <meta name="twitter:image" content="images/choose_OS.png" />

<meta name="author" content="Agustín Alesso">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="introduccion-a-ggplot2.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="1" data-path="empezando-con-r-y-rstudio.html"><a href="empezando-con-r-y-rstudio.html"><i class="fa fa-check"></i><b>1</b> Empezando con R y RStudio</a><ul>
<li class="chapter" data-level="1.1" data-path="empezando-con-r-y-rstudio.html"><a href="empezando-con-r-y-rstudio.html#que-es-r-y-rstudio"><i class="fa fa-check"></i><b>1.1</b> ¿Qué es R y RStudio?</a></li>
<li class="chapter" data-level="1.2" data-path="empezando-con-r-y-rstudio.html"><a href="empezando-con-r-y-rstudio.html#como-instalar-r-y-rstudio"><i class="fa fa-check"></i><b>1.2</b> ¿Cómo instalar R y RStudio?</a><ul>
<li class="chapter" data-level="1.2.1" data-path="empezando-con-r-y-rstudio.html"><a href="empezando-con-r-y-rstudio.html#instalacion-de-r"><i class="fa fa-check"></i><b>1.2.1</b> Instalación de R</a></li>
<li class="chapter" data-level="1.2.2" data-path="empezando-con-r-y-rstudio.html"><a href="empezando-con-r-y-rstudio.html#instalacion-de-rstudio"><i class="fa fa-check"></i><b>1.2.2</b> Instalación de RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="empezando-con-r-y-rstudio.html"><a href="empezando-con-r-y-rstudio.html#primera-sesion"><i class="fa fa-check"></i><b>1.3</b> Primera sesión</a><ul>
<li class="chapter" data-level="1.3.1" data-path="empezando-con-r-y-rstudio.html"><a href="empezando-con-r-y-rstudio.html#la-consola"><i class="fa fa-check"></i><b>1.3.1</b> La consola</a></li>
<li class="chapter" data-level="1.3.2" data-path="empezando-con-r-y-rstudio.html"><a href="empezando-con-r-y-rstudio.html#el-script"><i class="fa fa-check"></i><b>1.3.2</b> El script</a></li>
<li class="chapter" data-level="1.3.3" data-path="empezando-con-r-y-rstudio.html"><a href="empezando-con-r-y-rstudio.html#proyecto"><i class="fa fa-check"></i><b>1.3.3</b> Proyecto</a></li>
<li class="chapter" data-level="1.3.4" data-path="empezando-con-r-y-rstudio.html"><a href="empezando-con-r-y-rstudio.html#ayuda"><i class="fa fa-check"></i><b>1.3.4</b> Ayuda!!!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html"><i class="fa fa-check"></i><b>2</b> Aspectos básicos del lenguaje R</a><ul>
<li class="chapter" data-level="2.1" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#operadores-matematicos"><i class="fa fa-check"></i><b>2.1</b> Operadores matemáticos</a></li>
<li class="chapter" data-level="2.2" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#operadores-logicos"><i class="fa fa-check"></i><b>2.2</b> Operadores lógicos</a></li>
<li class="chapter" data-level="2.3" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#variables-y-objetos"><i class="fa fa-check"></i><b>2.3</b> Variables y objetos</a></li>
<li class="chapter" data-level="2.4" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#funciones-y-argumentos"><i class="fa fa-check"></i><b>2.4</b> Funciones y argumentos</a></li>
<li class="chapter" data-level="2.5" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#vectores"><i class="fa fa-check"></i><b>2.5</b> Vectores</a></li>
<li class="chapter" data-level="2.6" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#tipos-de-datos"><i class="fa fa-check"></i><b>2.6</b> Tipos de datos</a><ul>
<li class="chapter" data-level="2.6.1" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#numericos-numeric"><i class="fa fa-check"></i><b>2.6.1</b> Numéricos (<code>numeric</code>)</a></li>
<li class="chapter" data-level="2.6.2" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#texto-character"><i class="fa fa-check"></i><b>2.6.2</b> Texto (<code>character</code>)</a></li>
<li class="chapter" data-level="2.6.3" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#logicos-logic"><i class="fa fa-check"></i><b>2.6.3</b> Lógicos (<code>logic</code>)</a></li>
<li class="chapter" data-level="2.6.4" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#otros"><i class="fa fa-check"></i><b>2.6.4</b> Otros</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#estructura-de-datos"><i class="fa fa-check"></i><b>2.7</b> Estructura de datos</a><ul>
<li class="chapter" data-level="2.7.1" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#matriz-matrix"><i class="fa fa-check"></i><b>2.7.1</b> Matriz (<code>matrix</code>)</a></li>
<li class="chapter" data-level="2.7.2" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#listas-list"><i class="fa fa-check"></i><b>2.7.2</b> Listas (<code>list</code>)</a></li>
<li class="chapter" data-level="2.7.3" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#hoja-de-datos-data.frame"><i class="fa fa-check"></i><b>2.7.3</b> Hoja de datos (<code>data.frame</code>)</a></li>
<li class="chapter" data-level="2.7.4" data-path="aspectos-basicos-del-lenguaje-r.html"><a href="aspectos-basicos-del-lenguaje-r.html#factores-factor-y-ordered"><i class="fa fa-check"></i><b>2.7.4</b> Factores (<code>factor</code> y <code>ordered</code>)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html"><i class="fa fa-check"></i><b>3</b> Introducción a <code>dplyr</code></a><ul>
<li class="chapter" data-level="3.1" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html#que-es-dplyr"><i class="fa fa-check"></i><b>3.1</b> ¿Qué es <code>dplyr</code>?</a></li>
<li class="chapter" data-level="3.2" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html#como-conseguir-dplyr"><i class="fa fa-check"></i><b>3.2</b> ¿Cómo conseguir <code>dplyr</code>?</a></li>
<li class="chapter" data-level="3.3" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html#verbos-importantes-de-dplyr-para-recordar"><i class="fa fa-check"></i><b>3.3</b> Verbos importantes de <code>dplyr</code> para recordar</a></li>
<li class="chapter" data-level="3.4" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html#dplyr-en-accion"><i class="fa fa-check"></i><b>3.4</b> <code>dplyr</code> en acción</a><ul>
<li class="chapter" data-level="3.4.1" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html#seleccionando-variables"><i class="fa fa-check"></i><b>3.4.1</b> Seleccionando variables</a></li>
<li class="chapter" data-level="3.4.2" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html#seleccionando-observaciones"><i class="fa fa-check"></i><b>3.4.2</b> Seleccionando observaciones</a></li>
<li class="chapter" data-level="3.4.3" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html#encadenando-operaciones-operador"><i class="fa fa-check"></i><b>3.4.3</b> Encadenando operaciones (operador <code>%&gt;%</code>)</a></li>
<li class="chapter" data-level="3.4.4" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html#ordenar-las-filas"><i class="fa fa-check"></i><b>3.4.4</b> Ordenar las filas</a></li>
<li class="chapter" data-level="3.4.5" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html#crear-o-transformar-columnas"><i class="fa fa-check"></i><b>3.4.5</b> Crear o transformar columnas</a></li>
<li class="chapter" data-level="3.4.6" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html#resmuir-datos"><i class="fa fa-check"></i><b>3.4.6</b> Resmuir datos</a></li>
<li class="chapter" data-level="3.4.7" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html#agrupar-ultimo-pero-no-menos-importante"><i class="fa fa-check"></i><b>3.4.7</b> Agrupar (último pero no menos importante)</a></li>
<li class="chapter" data-level="3.4.8" data-path="introduccion-a-dplyr.html"><a href="introduccion-a-dplyr.html#muestrear"><i class="fa fa-check"></i><b>3.4.8</b> Muestrear</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduccion-a-ggplot2.html"><a href="introduccion-a-ggplot2.html"><i class="fa fa-check"></i><b>4</b> Introducción a <code>ggplot2</code></a><ul>
<li class="chapter" data-level="4.1" data-path="introduccion-a-ggplot2.html"><a href="introduccion-a-ggplot2.html#sistemas-de-graficos-en-r"><i class="fa fa-check"></i><b>4.1</b> Sistemas de gráficos en <strong>R</strong></a></li>
<li class="chapter" data-level="4.2" data-path="introduccion-a-ggplot2.html"><a href="introduccion-a-ggplot2.html#como-conseguir-ggplot2"><i class="fa fa-check"></i><b>4.2</b> ¿Cómo conseguir <code>ggplot2</code>?</a></li>
<li class="chapter" data-level="4.3" data-path="introduccion-a-ggplot2.html"><a href="introduccion-a-ggplot2.html#partes-basicas-de-un-grafico"><i class="fa fa-check"></i><b>4.3</b> Partes básicas de un gráfico</a></li>
<li class="chapter" data-level="4.4" data-path="introduccion-a-ggplot2.html"><a href="introduccion-a-ggplot2.html#todo-en-un-solo-paso"><i class="fa fa-check"></i><b>4.4</b> Todo en un solo paso</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html"><i class="fa fa-check"></i><b>5</b> Revisión de estadística básica</a><ul>
<li class="chapter" data-level="5.1" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#que-es-la-estadistica"><i class="fa fa-check"></i><b>5.1</b> ¿Qué es la estadística?</a></li>
<li class="chapter" data-level="5.2" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#variables"><i class="fa fa-check"></i><b>5.2</b> Variables</a><ul>
<li class="chapter" data-level="5.2.1" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#tipos-de-datos-1"><i class="fa fa-check"></i><b>5.2.1</b> Tipos de datos</a></li>
<li class="chapter" data-level="5.2.2" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#escala-de-medicion"><i class="fa fa-check"></i><b>5.2.2</b> Escala de medición</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#poblacion-y-muestra"><i class="fa fa-check"></i><b>5.3</b> Población y muestra</a></li>
<li class="chapter" data-level="5.4" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#estadistica-descriptiva"><i class="fa fa-check"></i><b>5.4</b> Estadística descriptiva</a><ul>
<li class="chapter" data-level="5.4.1" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#tablas-de-frecuencias"><i class="fa fa-check"></i><b>5.4.1</b> Tablas de frecuencias</a></li>
<li class="chapter" data-level="5.4.2" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#graficos"><i class="fa fa-check"></i><b>5.4.2</b> Gráficos</a></li>
<li class="chapter" data-level="5.4.3" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#medidas-de-resumen"><i class="fa fa-check"></i><b>5.4.3</b> Medidas de resumen</a></li>
<li class="chapter" data-level="5.4.4" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#grafico-de-caja"><i class="fa fa-check"></i><b>5.4.4</b> Gráfico de caja</a></li>
<li class="chapter" data-level="5.4.5" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#medidas-de-forma"><i class="fa fa-check"></i><b>5.4.5</b> Medidas de forma</a></li>
<li class="chapter" data-level="5.4.6" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#todas-las-medidas-juntas"><i class="fa fa-check"></i><b>5.4.6</b> Todas las medidas juntas</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#distribuciones-directamente-la-normal-y-tcl"><i class="fa fa-check"></i><b>5.5</b> distribuciones (directamente la normal y TCL)</a></li>
<li class="chapter" data-level="5.6" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#ic"><i class="fa fa-check"></i><b>5.6</b> IC</a></li>
<li class="chapter" data-level="5.7" data-path="revision-de-estadistica-basica.html"><a href="revision-de-estadistica-basica.html#test-hipotesis"><i class="fa fa-check"></i><b>5.7</b> Test hipotesis</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introducción al diseño y análisis estadístico de experimentos usando R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="revision-de-estadistica-basica" class="section level1">
<h1><span class="header-section-number">Capítulo 5</span> Revisión de estadística básica</h1>
<p>En este capítulo revisaremos algunos conceptos y términos estadísticos básicos que necesitaremos para el entender el diseño y análisis estadístico de datos provenientes de estudios observacionales y experimentales. Revisaremos:</p>
<ul>
<li>Concepto y utilidad de la Estadística</li>
<li>Tipos de datos y variables</li>
<li>Población y muestra</li>
<li>Estadística descriptiva</li>
<li>Distribuciones de probabilidades</li>
<li>Inferencia estadística</li>
</ul>
<div id="que-es-la-estadistica" class="section level2">
<h2><span class="header-section-number">5.1</span> ¿Qué es la estadística?</h2>
<p>Existen muchas definiciones de <em>Estadística</em>, tantas como libros consultemos. Según Ott y Longnecker (2016), la estadística es la ciencia del diseño de estudios o experimentos, recolección de datos y modelado/análisis de los mismos para la toma de decisiones o descubrimiento de nuevo conocimiento cuando la información disponible es limitada y variable. En resumen, <strong>la estadística es la ciencia del aprendizaje a partir de los datos</strong> (<em>learning from data</em>) y está muy emparentada con la aplicación del <strong>método científico</strong>.</p>
<p>Según este enfoque, el proceso de aprender a partir de los datos implica las siguientes etapas:
1. <strong>Definición del problema de estudio.</strong> Todo estudio o investigación surge de una pregunta de investigación, un interrogante sobre nuestro objeto de estudio que no ha sido respondido aún con la información existente. Esto motiva la búsqueda de más información (nuevos experimentos o muestreos) para verificar las posibles respuestas o modelos que nos permitan representarlo (hipótesis). Entonces, a partir de la identificación del problema o pregunta de estudio ponemos de relieve cuáles son las variables que intervienen en el proceso, cuáles hay que controlar y cuáles hay que alterar para ver la respuesta, cuál es la información que debemos recolectar, que tipo de datos se van a trabajar, etc.</p>
<ol start="2" style="list-style-type: decimal">
<li><p><strong>Recolección de los datos.</strong> Una vez definido el problema de estudio, necesitamos determinar de qué manera se colectará la información relevante. Para ello debemos diseñar muestreos o experimentos que permitan de manera costo efectiva obtener la mayor cantidad de información empleando el menor tiempo y dinero para lograr responder de manera precisa la pregunta que originó el estudio. La estadísitca brinda herramientas para el esto.</p></li>
<li><p><strong>Resumen de la información.</strong> con los datos en mano debemos organizadorlos y resumirlos mediante técnicas núméricas o gráficas para facilitar su exploración y el reconocimiento de las principales características o patrones de los mismos (tendencias, variabilidad, anomalías, etc.). La <em>estadística descriptiva</em> brinda las herramientas necesarias para la descripción de la información proveniente de muestreos o experimentos.</p></li>
<li><p><strong>Análisis, interpretación y comunicación de los resultados.</strong> Los datos obtenidos son una pequeña parte (<em>muestra</em>) de un conjunto más grande (<em>población</em>) el cual es imposible observar en su totalidad. Debemos analizar la información de la muestra para realizar generalizaciones y poder interpretar los resultados en la población. La <em>estadística inferencial</em> brinda herramientas para estimar y valorar los modelos definidos en la Etapa 1 a la luz de los datos recolectados en la Etapa 2 considerando la variabilidad del proceso que los generó.</p></li>
</ol>
</div>
<div id="variables" class="section level2">
<h2><span class="header-section-number">5.2</span> Variables</h2>
<p>Las variables son características de interés que se observan o miden en la unidad de observación más pequeña. Al contrario que las constantes, las variables toman diferentes valores de una individuo a otro, i.e. varían. Podemos clasificar las variables según el tipo de datos e información que contienen.</p>
<div id="tipos-de-datos-1" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Tipos de datos</h3>
<p>Según el tipo de datos, las variables son:</p>
<ul>
<li><em>Cualitativas</em>: que expresan una <strong>cualidad</strong> o atributo no numéricos. <em>e.g. color de pelo, sexo, estatus sanitario, estado fenológico.</em></li>
<li><em>Cuantitativas</em>: que expresan una <strong>cantidad discreta</strong> (<em>e.g. número de ramas, número de insectos</em>) o <strong>contínua</strong> (<em>e.g. peso de granos, contenido de MO del suelo</em>).</li>
</ul>
</div>
<div id="escala-de-medicion" class="section level3">
<h3><span class="header-section-number">5.2.2</span> Escala de medición</h3>
<p>Según la cantidad de información que contienen (de menor a mayor) las variables se clasifican en:</p>
<ul>
<li><strong>Nominal</strong>: cualitativa (<em>el número de identificación o RP de una vaca</em>)</li>
<li><strong>Ordinal</strong>: cualitativa con orden (<em>posición en el ranking del control lechero</em>)</li>
<li><strong>De intervalo</strong>: cuantitativa, orden y distancias (<em>fecha del último parto</em>)</li>
<li><strong>De razón</strong>: cuantitativa, orden, distancia y proporciones (<em>días desde el último parto</em>)</li>
</ul>
<p>La escala de medición determina la cantidad de información que tienen y qué métodos podemos aplicar. Siempre podemos analizar variables más completas con técnicas para variables más simples. No obstante, este procedimiento implica pérdida información que puede ser relevante para responder la pregunta de investigación. Por ejemplo, una variable numérica de intervalo o razón podemos convertirla en nominal u ordinal generando intervalos de clases y contabilizar las frecuencias de cada clase. Por el contrario, las variables más simples no pueden ser analizadas con técnicas diseñadas para variables más completas. Ejemplo: no podemos obtener el promedio de una variable <em>nominal</em> como el color de pelo.</p>
</div>
</div>
<div id="poblacion-y-muestra" class="section level2">
<h2><span class="header-section-number">5.3</span> Población y muestra</h2>
<p>Desde el punto de vista estadístico, una <strong>Población</strong> es la totalidad de las unidades u observaciones individuales sobre la cuales queremos <em>realizar la inferencia</em>. Está <em>definida en el tiempo y espacio</em> y se caracteriza por sus <em>parámetros</em>, i.e. la media <span class="math inline">\(\mu\)</span>. Las poblaciones pueden ser finitas, i.e. podemos contar la totalidad de elementos que contienen, o infinita, i.e. no los podemos contar. En la mayoría de los casos, los métodos estadísticos asumen que la población es infinita o finitas pero tan grandes que a los efectos prácticos puede asumirse que son infinitas.</p>
<p>Por su parte, una <strong>muestra</strong> es un subconjunto de individuos u observaciones individuales que elegimos de la población. Las muestras son finitas y se caracterizan por sus <em>estadísticos</em> que son la versión muestral de los parámetros poblacionales, i.e. la media muestral <span class="math inline">\(\bar{y}\)</span>. Si el procedimiento que utilizamos para obtener la muestra es aleatorio entonces podemos asumir que la muestra tendrá las mismas propiedades que la población y por lo tanto podemos usar dicha información para inferencia características de la poblaicón. En el siguiente gráfico resume el concepto general de la inferencia estadística.</p>
<div class="figure"><span id="fig:unnamed-chunk-82"></span>
<img src="images/poblacion_muestra_venn.svg" alt="Esquema del proceso de inferencia estadística" width="80%" />
<p class="caption">
Figure 5.1: Esquema del proceso de inferencia estadística
</p>
</div>
<p>Supongamos que queremos conocer el valor medio de las alturas (<em>parámetro</em>) en m de plantas de maíz de un lote de 50 has, i.e. <span class="math inline">\(\mu = ?\)</span>. El conjunto más grande denominado <em>Población</em> contiene las alturas en m de todas las plantas de maíz del lote en estudio y sobre el que se quiere hacer la inferencia (los <span class="math inline">\(\dots\)</span> indican que en el gráfico no están representados todos los valores). Cada planta es una <em>unidad de muestreo</em> porque la elegimos individualmente, y una <em>unidad observacional</em> porque a cada planta le medimos la altura (observación). Aquellas alturas en rojo corresponden a las 6 plantas que seleccionamos mediante un <em>muestreo aleatorio</em> para componer la muestra (<span class="math inline">\(n = 6\)</span>). La altura promedio de las plantas de la muestra (<em>estadístico</em>) es <span class="math inline">\(\bar{y} = 1.728\)</span>. Dado que el muestreo fue realizado al azar, el estadístico calculado a partir de la muestra brinda información sobre lo que pasa a nivel poblacional (<span class="math inline">\(\mu\)</span>). A su vez, la aleatoriedad del muestreo determina que si repitieramos el muestreo de 6 unidades muchas veces, el estadístico muestral tomaría distintos valores cada vez ya que es una <em>variable aleatoria</em>. Finalmente, a partir de la <em>distribución de probabilidades</em> asociada a los posibles valores que tomaría el estadístico muestral podemos realizar la inferencia sobre el parámetro poblacional incorporando la variabilidad del muestreo.</p>
</div>
<div id="estadistica-descriptiva" class="section level2">
<h2><span class="header-section-number">5.4</span> Estadística descriptiva</h2>
<p>La Estadística Descriptiva la rama de la Estadísica que comprende las técnicas y métodos para organizar, resumir y describir conjuntos de datos de distinto tipo recolectados en muestreos o censos.</p>
<div id="tablas-de-frecuencias" class="section level3">
<h3><span class="header-section-number">5.4.1</span> Tablas de frecuencias</h3>

<p>Conocer la distribución de los valores de las variables en estudio es importante para examinar algunas características tales como la tendencia central, la dispersión, presencia de valores atípicos, etc.</p>
<p>Una forma de examinar al distribución es mediante <em>tablas de frecuencias</em> que consisten en el listado de los valores de la variable (individuales o agrupados en <strong>clases</strong>) y sus <strong>frecuencias</strong> o conteos correspondientes. Es útil para resumir variables categóricas, discretas o conjuntos de datos cuantitativos contínuos grandes <span class="math inline">\(n &gt; 25\)</span>.</p>
<p>Las frecuencias representan el número de veces que un valor o clase está representado en la muestra o población. Para ejemplificar la construcción de tablas de frecuencias en <strong>R</strong> usaremos datos de pesaje de terneros de un establecimiento ganadero del norte de Santa Fe. Los datos encuentran en el archivo <a href="https://github.com/agustin-alesso/intro_DOE_R/raw/master/data/pesada_terneros.xlsx"><code>pesada_terneros.xlsx</code></a>.</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" title="1"><span class="co"># Cargar los datos</span></a>
<a class="sourceLine" id="cb173-2" title="2"><span class="kw">library</span>(readxl)</a>
<a class="sourceLine" id="cb173-3" title="3">terneros &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;pesada_terneros.xlsx&quot;</span>)</a>
<a class="sourceLine" id="cb173-4" title="4">terneros</a></code></pre></div>
<pre><code>## # A tibble: 1,598 x 4
##    IDV       Procedencia Fecha                Peso
##    &lt;chr&gt;     &lt;chr&gt;       &lt;dttm&gt;              &lt;dbl&gt;
##  1 NR047A202 La Rosita   2017-04-06 00:00:00   204
##  2 GN685B267 La Rosita   2017-04-06 00:00:00   186
##  3 AI101A751 La Rosita   2017-04-06 00:00:00   182
##  4 TM603C877 La Rosita   2017-04-06 00:00:00   186
##  5 TM420B797 La Rosita   2017-04-06 00:00:00   186
##  6 LH837F500 La Rosita   2017-04-06 00:00:00   208
##  7 NR047A217 La Rosita   2017-04-06 00:00:00   170
##  8 LH837F508 La Rosita   2017-04-06 00:00:00   188
##  9 GN685B256 La Rosita   2017-04-06 00:00:00   172
## 10 QW110A058 La Rosita   2017-04-06 00:00:00   172
## # ... with 1,588 more rows</code></pre>
<p>Primero hay que definir el número de *<strong>intervalos de clases</strong> y sus <strong>límites de clase</strong> (inferior <span class="math inline">\(\text{LI}\)</span> y superior <span class="math inline">\(\text{LS}\)</span>). Generalmente se consideran semiabiertos a derecha <code>[ )</code> y si bien no hay un criterio estricto para determinar el número de clases, se recomiendan entre 5 y 20 clases de igual amplitud es adecuado. El número depende de la dispersión total de los datos y la cantidad de datos.</p>
<p>Una forma de hacerlo es mediante la función <code>pretty()</code> que utiliza un algoritmo para obtener números de clases que tengan límites <em>redondo</em>. Con el argumento <code>n = 8</code> se le sugiere un número tentativo de clases. El algoritmo en función de la variabiliad de los datos puede sugerir más o menos intervalos.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb175-1" title="1"><span class="co"># Definir los intervalos</span></a>
<a class="sourceLine" id="cb175-2" title="2">lim &lt;-<span class="st"> </span><span class="kw">with</span>(terneros, <span class="kw">pretty</span>(Peso, <span class="dt">n =</span> <span class="dv">8</span>))</a>
<a class="sourceLine" id="cb175-3" title="3">lim</a></code></pre></div>
<pre><code>## [1]  50 100 150 200 250 300 350 400</code></pre>
<p>La diferencia o distancia entre dos <span class="math inline">\(\text{LI}\)</span> o <span class="math inline">\(\text{LS}\)</span> consecutivos se denomina <strong>amplitud de clase</strong>, <span class="math inline">\(c = \text{LI}_{i} - \text{LI}_{i-1}\)</span> y la <strong>marca de clase</strong> es el valor central de la clase, i.e. promedio entre los límites o bien <span class="math inline">\(\text{MC}= \text{LI}+ 0.5 c\)</span>. En este caso la amplitud de las clases sugeridas por <code>pretty()</code> es de 50 kg. Las marcas de clases se obtienen sumando media amplitud a los límites inferiores.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb177-1" title="1">c &lt;-<span class="st"> </span><span class="dv">50</span></a>
<a class="sourceLine" id="cb177-2" title="2">mc &lt;-<span class="st"> </span>lim[<span class="dv">1</span><span class="op">:</span><span class="dv">7</span>] <span class="op">+</span><span class="st"> </span><span class="fl">0.5</span> <span class="op">*</span><span class="st"> </span>c</a>
<a class="sourceLine" id="cb177-3" title="3">mc</a></code></pre></div>
<pre><code>## [1]  75 125 175 225 275 325 375</code></pre>
<p>con los límites definidos se debe categorizar o discretizar la variable contínua, es decir, transformar el vector <code>Peso</code> en un vector contenga el intervalo al que pertenece cada valor de peso observado. Esto se hace con la función <code>cut()</code> indicando los límites de clase en <code>breaks</code>. El argumento <code>include.lowest = T</code> es para aseguramos que todos los datos sean incluidos en las clases y <code>right = F</code> para que los intervalos no sean cerrados a derecha, es decir, que sean semi-abiertos a derecha. Con la función <code>mutate()</code> de <code>dplyr</code> creamos una nueva columna en el set de datos con las clases que contiene.</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb179-1" title="1"><span class="co"># Dividir los datos en clases</span></a>
<a class="sourceLine" id="cb179-2" title="2"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb179-3" title="3">terneros &lt;-<span class="st"> </span><span class="kw">mutate</span>(terneros, <span class="dt">clases =</span> <span class="kw">cut</span>(Peso, <span class="dt">breaks =</span> lim, <span class="dt">include.lowest =</span> T, <span class="dt">right =</span> F))</a>
<a class="sourceLine" id="cb179-4" title="4">terneros</a></code></pre></div>
<pre><code>## # A tibble: 1,598 x 5
##    IDV       Procedencia Fecha                Peso clases   
##    &lt;chr&gt;     &lt;chr&gt;       &lt;dttm&gt;              &lt;dbl&gt; &lt;fct&gt;    
##  1 NR047A202 La Rosita   2017-04-06 00:00:00   204 [200,250)
##  2 GN685B267 La Rosita   2017-04-06 00:00:00   186 [150,200)
##  3 AI101A751 La Rosita   2017-04-06 00:00:00   182 [150,200)
##  4 TM603C877 La Rosita   2017-04-06 00:00:00   186 [150,200)
##  5 TM420B797 La Rosita   2017-04-06 00:00:00   186 [150,200)
##  6 LH837F500 La Rosita   2017-04-06 00:00:00   208 [200,250)
##  7 NR047A217 La Rosita   2017-04-06 00:00:00   170 [150,200)
##  8 LH837F508 La Rosita   2017-04-06 00:00:00   188 [150,200)
##  9 GN685B256 La Rosita   2017-04-06 00:00:00   172 [150,200)
## 10 QW110A058 La Rosita   2017-04-06 00:00:00   172 [150,200)
## # ... with 1,588 more rows</code></pre>
<p>De este modo cada valor de peso queda asociado a una clase. Luego haciendo el conteo de clases se obtiene las frecuencias usando <code>n</code></p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb181-1" title="1"><span class="co"># Obtener frecuencias simples absolutas</span></a>
<a class="sourceLine" id="cb181-2" title="2">tabla &lt;-<span class="st"> </span><span class="kw">count</span>(terneros, clases)</a>
<a class="sourceLine" id="cb181-3" title="3">tabla</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   clases        n
##   &lt;fct&gt;     &lt;int&gt;
## 1 [50,100)      4
## 2 [100,150)   296
## 3 [150,200)   812
## 4 [200,250)   405
## 5 [250,300)    80
## 6 [350,400]     1</code></pre>
<p>como no aparece la categoría <code>[300, 350)</code> hay que agregarla usando <code>complete()</code> del paquete <code>tidyr</code>.</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" title="1"><span class="co"># Rellenar con clases faltantes</span></a>
<a class="sourceLine" id="cb183-2" title="2"><span class="kw">library</span>(tidyr)</a>
<a class="sourceLine" id="cb183-3" title="3">tabla &lt;-<span class="st"> </span><span class="kw">complete</span>(tabla, clases, <span class="dt">fill =</span> <span class="kw">list</span>(<span class="dt">n =</span> <span class="dv">0</span>))</a>
<a class="sourceLine" id="cb183-4" title="4">tabla</a></code></pre></div>
<pre><code>## # A tibble: 7 x 2
##   clases        n
##   &lt;fct&gt;     &lt;dbl&gt;
## 1 [50,100)      4
## 2 [100,150)   296
## 3 [150,200)   812
## 4 [200,250)   405
## 5 [250,300)    80
## 6 [300,350)     0
## 7 [350,400]     1</code></pre>
<p>Esta tabla representa la distribución de los valores de cos de terneros. Se observa que la mayoría de los animales registró un peso de entre 150 y 200 kg ya que es el intervalo más frecuente. Existen algunos pocos terneros con cos llamativamente bajos y altos. La gran mayoría de los cos fueron entre 100 y 250 kg.</p>
<p>Las frecuencias definidas hasta aquí se denominan <strong>frecuencias simples absolutas</strong> ya que representan el conteo de las cases. Cuando ese conteo se expresa en relación al total pasan a ser <strong>frecuencias simples relativas</strong> (<span class="math inline">\(h_i = n_i/n\)</span>). Estas frecuencias pueden se pueden expresar de manera que muestren el número de veces que un valor o clase y los anteriores están representado en la muestra o población. Así se obtienen las <strong>frecuencias acumuladas absolutas</strong> (<span class="math inline">\(F_i\)</span>) y <strong>relativas</strong> (<span class="math inline">\(H_i = F_i/n\)</span>).</p>
<p>Para agregar estas frecuencias y marcas de clase:</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" title="1"><span class="co"># Agregar otras frecuencias</span></a>
<a class="sourceLine" id="cb185-2" title="2">tabla &lt;-<span class="st"> </span><span class="kw">mutate</span>(tabla, <span class="dt">mc =</span> mc, <span class="dt">F =</span> <span class="kw">cumsum</span>(n), <span class="dt">h =</span> n<span class="op">/</span><span class="kw">sum</span>(n), <span class="dt">H =</span> F<span class="op">/</span><span class="kw">sum</span>(n))</a>
<a class="sourceLine" id="cb185-3" title="3">tabla</a></code></pre></div>
<pre><code>## # A tibble: 7 x 6
##   clases        n    mc     F        h       H
##   &lt;fct&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 [50,100)      4    75     4 0.00250  0.00250
## 2 [100,150)   296   125   300 0.185    0.188  
## 3 [150,200)   812   175  1112 0.508    0.696  
## 4 [200,250)   405   225  1517 0.253    0.949  
## 5 [250,300)    80   275  1597 0.0501   0.999  
## 6 [300,350)     0   325  1597 0        0.999  
## 7 [350,400]     1   375  1598 0.000626 1</code></pre>
<p>Esta tabla nos permite conocer cerca del 50% de los datos estan contenidos en el rango <code>[150, 200)</code> kg.</p>
<p>Los comandos anteriormente vistos se pueden encadenar con el operador <code>%&gt;%</code> para obtener de manera más compacta la tabla anterior:</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb187-1" title="1"><span class="co"># Paquetes necesarios</span></a>
<a class="sourceLine" id="cb187-2" title="2"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb187-3" title="3"><span class="kw">library</span>(tidyr)</a>
<a class="sourceLine" id="cb187-4" title="4"></a>
<a class="sourceLine" id="cb187-5" title="5"><span class="co"># Limites y marcas de clase</span></a>
<a class="sourceLine" id="cb187-6" title="6">lim &lt;-<span class="st"> </span><span class="kw">pretty</span>(terneros<span class="op">$</span>Peso, <span class="dt">n =</span> <span class="dv">8</span>)</a>
<a class="sourceLine" id="cb187-7" title="7">c &lt;-<span class="st"> </span><span class="dv">50</span></a>
<a class="sourceLine" id="cb187-8" title="8">mc &lt;-<span class="st"> </span>lim[<span class="dv">1</span><span class="op">:</span><span class="dv">7</span>] <span class="op">+</span><span class="st"> </span><span class="fl">0.5</span> <span class="op">*</span><span class="st"> </span>c</a>
<a class="sourceLine" id="cb187-9" title="9"></a>
<a class="sourceLine" id="cb187-10" title="10"><span class="co"># Tabla de frecuencias</span></a>
<a class="sourceLine" id="cb187-11" title="11">tabla &lt;-<span class="st"> </span>terneros <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb187-12" title="12"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">clases =</span> <span class="kw">cut</span>(Peso, <span class="dt">breaks =</span> lim, <span class="dt">include.lowest =</span> T, <span class="dt">right =</span> F)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb187-13" title="13"><span class="st">  </span><span class="kw">count</span>(clases) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb187-14" title="14"><span class="st">  </span><span class="kw">complete</span>(clases, <span class="dt">fill =</span> <span class="kw">list</span>(<span class="dt">n =</span> <span class="dv">0</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb187-15" title="15"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mc =</span> mc, <span class="dt">F =</span> <span class="kw">cumsum</span>(n), <span class="dt">h =</span> n<span class="op">/</span><span class="kw">sum</span>(n), <span class="dt">H =</span> F<span class="op">/</span><span class="kw">sum</span>(n))</a>
<a class="sourceLine" id="cb187-16" title="16">tabla</a></code></pre></div>
<pre><code>## # A tibble: 7 x 6
##   clases        n    mc     F        h       H
##   &lt;fct&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 [50,100)      4    75     4 0.00250  0.00250
## 2 [100,150)   296   125   300 0.185    0.188  
## 3 [150,200)   812   175  1112 0.508    0.696  
## 4 [200,250)   405   225  1517 0.253    0.949  
## 5 [250,300)    80   275  1597 0.0501   0.999  
## 6 [300,350)     0   325  1597 0        0.999  
## 7 [350,400]     1   375  1598 0.000626 1</code></pre>
</div>
<div id="graficos" class="section level3">
<h3><span class="header-section-number">5.4.2</span> Gráficos</h3>
<p>La distribución de los datos también se puede representar de manera gráfica. Existen varias técnicas que se complementan.</p>
<div id="histograma" class="section level4">
<h4><span class="header-section-number">5.4.2.1</span> Histograma</h4>
<p>El <strong>histograma</strong> es la representación gráfica de la tabla de frecuencias vista anteriormente. Consiste en graficar las frecuencias (simples, absolutas o relativas) mediante barras sobre un eje horizontal que representa la variable en estudio. La altura de las barras representa las frecuencias y el ancho la amplitud del intervalo de clase.</p>
<p>En <strong>R</strong> mediante el paquete <code>ggplot2</code> podemos graficar histogramas con distinta cantidad y amplitud de clases combinando los argumentos <code>bins</code> y <code>binwidth</code>. Por ejemplo, un histograma con 8 clases para los datos peso de terneros sería:</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb189-1" title="1"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb189-2" title="2">p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(terneros) <span class="op">+</span><span class="st"> </span><span class="kw">aes</span>(<span class="dt">x =</span> Peso)</a>
<a class="sourceLine" id="cb189-3" title="3">p <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">8</span>)</a></code></pre></div>
<p><img src="intro-DOE-R_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<p>Achicando el ancho de clases:</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb190-1" title="1">p <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">25</span>)</a></code></pre></div>
<p><img src="intro-DOE-R_files/figure-html/unnamed-chunk-93-1.png" width="672" /></p>
<p>En el caso de variabls discretas, las barras se grafican separadas. Supongamos que queremos graficar las frecuencias de la variable <code>Procedencia</code>.</p>
<p><img src="intro-DOE-R_files/figure-html/unnamed-chunk-94-1.png" width="672" /></p>
</div>
</div>
<div id="medidas-de-resumen" class="section level3">
<h3><span class="header-section-number">5.4.3</span> Medidas de resumen</h3>
<p>Las medidas de resumen son funciones que permiten extraer información relevante de la distribución de los datos y expresarla de manera resumida mediante números. De acuerdo a la característica de la distribución que resumen se pueden clasificar en medidas de: <strong>tendencia central</strong>, <strong>dispersion</strong>, <strong>posición</strong> y <strong>forma</strong></p>
<p><strong>Algo de notación</strong></p>
<p>Si <span class="math inline">\(X\)</span> es un vector que representa una muestra con <span class="math inline">\(n\)</span> observaciones, cada elemento de <span class="math inline">\(X\)</span> se identifica por su orden mediante <span class="math inline">\(X_i\)</span> donde <span class="math inline">\(i\)</span> es la posición de la i-ésima observación.</p>
<p><strong>Ejemplo:</strong> si <span class="math inline">\(X = [1.73, 1.84, 1.92, 2]\)</span> son las alturas de 4 plantas de maiz, la altura de la planta 3 es <span class="math inline">\(X_i = 1.92\)</span></p>
<p><strong>R</strong> representa los datos de manera parecida:</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb191-1" title="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">1.73</span>, <span class="fl">1.84</span>, <span class="fl">1.92</span>, <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb191-2" title="2">x[<span class="dv">3</span>]</a></code></pre></div>
<pre><code>## [1] 1.92</code></pre>
<div id="medidas-de-tendencia-central" class="section level4">
<h4><span class="header-section-number">5.4.3.1</span> Medidas de tendencia central</h4>
<p>Resumen comportamiento de los datos más frecuentes, hacia donde se centra la distribución. Existen varias medidas las más comunes son la media, mediana y modo.</p>
<p>La <strong>media aritmética</strong>, es el centro de gravedad de los datos. Se define como el cociente entre la suma de los valores de la muestra y la cantidad observaciones:</p>
<p><span class="math display">\[
\bar{X} = \dfrac{1}{n} \sum_i^n x_i = \dfrac{\sum x_i}{n} = \dfrac{x_1 + x_2 + \cdots + x_n}{n}
\]</span></p>
<p><strong>Ejemplo:</strong> Los cos de 5 novillos son: 250, 230, 280, 235, 260. El peso promedio es:</p>
<p><span class="math display">\[
\bar{X} = \dfrac{250 + 230  + 280 + 235 + 260}{5} = 251
\]</span></p>
<p>Es la medida más común para representar la tendencia central de los datos y es fácil de calcular. Es un buen estimador de la media poblacional (<span class="math inline">\(\mu\)</span>). No obstante, es sensible a los valores extremos.</p>
<p>En <strong>R</strong> la función que calcula la media se denomina <code>mean()</code></p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb193-1" title="1"><span class="co"># peso promedio</span></a>
<a class="sourceLine" id="cb193-2" title="2"><span class="kw">mean</span>(terneros<span class="op">$</span>Peso)</a></code></pre></div>
<pre><code>## [1] 182.6546</code></pre>
<p>En promedio los terneros pesaron l82.65 kg.</p>
<p>Por su parte la <strong>mediana</strong> es el valor que separa al conjunto de datos (ordenados) en dos partes iguales. Es una medida robusta ya que no es afectada por los valores extremos.</p>
<p><span class="math display">\[ 
\tilde{X} = \begin{cases} \dfrac{x_{n/2} + x_{(n/2)+1}}{2} &amp;\text{si n es par} \\
x_{(n+1)/2} &amp;\text{si n es impar}
\end{cases}
\]</span></p>
<p>Si <span class="math inline">\(n\)</span> es par, <span class="math inline">\(\tilde{X}\)</span> es el promedio de los valores centrales (posiciones <span class="math inline">\(n/2\)</span> y <span class="math inline">\((n/2)+1\)</span>). Si <span class="math inline">\(n\)</span> es impar, <span class="math inline">\(\tilde{X}\)</span> es el valor ubicado en la posicion <span class="math inline">\((n+1)/2\)</span></p>
<p>En <strong>R</strong> la función que calcula la mediana se denomina <code>median()</code>:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb195-1" title="1"><span class="co"># peso mediano</span></a>
<a class="sourceLine" id="cb195-2" title="2"><span class="kw">median</span>(terneros<span class="op">$</span>Peso)</a></code></pre></div>
<pre><code>## [1] 180</code></pre>
<p>El 50% de los terneros pesó igual o menos de 180 kg.</p>
</div>
<div id="medidas-de-dispersion" class="section level4">
<h4><span class="header-section-number">5.4.3.2</span> Medidas de dispersión</h4>
<p>Son medidas que resumen el grado de variabilidad de los datos. Entre las más comunes se encuentran el <strong>rango</strong>, <strong>varianza</strong> y <strong>desviación estándar</strong>.</p>
<p>El <strong>rango</strong> se define como la diferencia entre el valor máximo y mínimo de los datos. Es una medida muy simple pero altamente sensible a valores extremos ya que solamente usa la información del mínimo y máximo.</p>
<p><span class="math display">\[
\text{rango} = \text{max}(X) - \text{min}(X)
\]</span></p>
<p>En <strong>R</strong> el rango se obtiene de la misma manera mediante las funciones <code>max()</code> y <code>min()</code>.</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb197-1" title="1"><span class="co"># Calculo del rango</span></a>
<a class="sourceLine" id="cb197-2" title="2"><span class="kw">with</span>(terneros, <span class="kw">max</span>(Peso) <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(Peso))</a></code></pre></div>
<pre><code>## [1] 306</code></pre>
<p>Una medida mejor para expresar la variabilidad es la <strong>varianza</strong> (<span class="math inline">\(s^2\)</span>) que se define como el promedio de las desviacione cuadráticas de las observaciones respecto de la media.</p>
<p><span class="math display">\[
s^2 = \dfrac{\sum (x_i - \bar{X})^2}{n-1} = \dfrac{1}{n-1} \left[ \sum x_i^2 - \dfrac{(\sum x_i)^2}{n} \right]
\]</span></p>
<p>El denominador <span class="math inline">\(n-1\)</span> representa los grados de libertad, es decir, el número de datos de la muestra que pueden variar cuando se usa el estimador de la media <span class="math inline">\(\bar{X}\)</span>.</p>
<p>Dado que los desvíos respecto del promedio tienen la propiedad de cancelarse <span class="math inline">\(\sum (x_i - \bar{x}) = 0\)</span> los desvíos se deben elevar al cuadrado y esto a convierte una medida muy sensible a valores extremos.</p>
<p>La <strong>desviación estándar</strong> (<span class="math inline">\(s\)</span>) es la raiz cuadrada de la varianza</p>
<p><span class="math display">\[
s = \sqrt{s^2}
\]</span></p>
<p>La desviación estándar es interpretable ya que está en la escala original. Al igual que la varianza es sensible a valores extremos ya que utiliza <span class="math inline">\(\bar{X}\)</span> y los desvíos elevados al cuadrado.</p>
<p>En <strong>R</strong> la varianza y desvio se obtienen con <code>var()</code> y <code>sd()</code>.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" title="1"><span class="co"># Varianza</span></a>
<a class="sourceLine" id="cb199-2" title="2"><span class="kw">var</span>(terneros<span class="op">$</span>Peso)</a></code></pre></div>
<pre><code>## [1] 1383.534</code></pre>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" title="1"><span class="co"># Desvío</span></a>
<a class="sourceLine" id="cb201-2" title="2"><span class="kw">sd</span>(terneros<span class="op">$</span>Peso)</a></code></pre></div>
<pre><code>## [1] 37.19588</code></pre>
<p>Si bien la desviación estándar es interpretable ya que está en la misma escala que la variable original, a veces es conveniente expresarle en relación al promedio de los datos para compararlo con otros datos o variables. El <strong>coeficiente de variación</strong> (<span class="math inline">\(CV\)</span>) es una media de dispersión relativa para comparar la variabilidad entre muestras.</p>
<p><span class="math display">\[
CV = \dfrac{s}{\bar{X}}
\]</span></p>
<p>En <strong>R</strong> podemos obtenerlo combinando las funciones <code>sd()</code> y <code>mean()</code></p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb203-1" title="1"><span class="co"># CV de los cos</span></a>
<a class="sourceLine" id="cb203-2" title="2"><span class="kw">with</span>(terneros, <span class="kw">sd</span>(Peso)<span class="op">/</span><span class="kw">mean</span>(Peso))</a></code></pre></div>
<pre><code>## [1] 0.2036406</code></pre>
<p>Los pesos de los terneros varían un 20% en torno al promedio.</p>
</div>
<div id="medidas-de-posicion" class="section level4">
<h4><span class="header-section-number">5.4.3.3</span> Medidas de posición</h4>
<p>Los cuantiles son una generalización del concepto de la mediana. En <strong>R</strong> se calculan con la función <code>quantile()</code>. Cuando los datos se dividen en cuatro partes iguales se llaman <strong>cuartiles</strong> <span class="math inline">\((Q_i)\)</span>, si se divide en 10 partes iguales son <strong>deciles</strong> (<span class="math inline">\(D_i\)</span>) y para 100 partes iguales <strong>percentiles</strong> (<span class="math inline">\(P_i\)</span>).</p>
<p><span class="math display">\[
\tilde{X} = Q_2 = D_5 = P_{50}
\]</span></p>
<p>Una medida importante es el rango intercuartílico (<span class="math inline">\(IQR\)</span>) que indica entre que valores se encuentra el 50% central de la distribución de los datos</p>
<p><span class="math display">\[
IQR = Q_3 - Q_1
\]</span></p>
<p>Por ejemplo para obtener los valores de peso que separa a la muestra en 4 partes iguales:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb205-1" title="1"><span class="kw">with</span>(terneros, <span class="kw">quantile</span>(Peso, <span class="dt">probs =</span> <span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>)))</a></code></pre></div>
<pre><code>## 25% 50% 75% 
## 158 180 206</code></pre>
<p>o bien, ¿cuánto pesa el ternero más liviano del 20% de los terneros más pesados? Eso sería el percentil 0.8.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb207-1" title="1"><span class="kw">with</span>(terneros, <span class="kw">quantile</span>(Peso, <span class="dt">prob =</span> <span class="fl">0.8</span>))</a></code></pre></div>
<pre><code>##   80% 
## 213.2</code></pre>
<p>Para obtener el percentil que corresponde a un dato particular de la muestra se usa la <em>función empírica de distribución acumulada</em>.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb209-1" title="1"><span class="co"># Obtener la ECDF</span></a>
<a class="sourceLine" id="cb209-2" title="2">ecdf_peso &lt;-<span class="st"> </span><span class="kw">ecdf</span>(terneros<span class="op">$</span>Peso)</a>
<a class="sourceLine" id="cb209-3" title="3"></a>
<a class="sourceLine" id="cb209-4" title="4"><span class="co"># Obtener el percentil del peso = 213.2</span></a>
<a class="sourceLine" id="cb209-5" title="5"><span class="kw">ecdf_peso</span>(<span class="fl">213.2</span>)</a></code></pre></div>
<pre><code>## [1] 0.7997497</code></pre>
</div>
</div>
<div id="grafico-de-caja" class="section level3">
<h3><span class="header-section-number">5.4.4</span> Gráfico de caja</h3>
<p>Es una técnica propuesta por John Tukey para representar la distribución de los datos mediante un gráfico exploratorio basado en medidas robustas (mediana, cuartiles, etc). Permite ver la región central de los datos, el sesgo y la presencia datos atípicos leves y moderados</p>
<p><img src="intro-DOE-R_files/figure-html/unnamed-chunk-104-1.png" width="672" /></p>
<p>En el caso de los terneros, la distribución de los pesos se puede representar con un gráfico de cajas usando <code>geom_boxplot()</code></p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb211-1" title="1"><span class="co"># Boxplot peso terneros</span></a>
<a class="sourceLine" id="cb211-2" title="2"><span class="kw">ggplot</span>(terneros, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="st">&quot;&quot;</span>, <span class="dt">y =</span> Peso)) <span class="op">+</span></a>
<a class="sourceLine" id="cb211-3" title="3"><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb211-4" title="4"><span class="st">  </span><span class="kw">coord_flip</span>()</a></code></pre></div>
<p><img src="intro-DOE-R_files/figure-html/unnamed-chunk-105-1.png" width="672" /></p>
<p>Según este gráfico el 50% de la distribución esta entre 158 y 206 y el sesgo es pequeño. Por defecto el gráfico de caja muestra los valores atípicos leves y extremos ya que toma 1.5 veces el rango intercuartilico. Para determinar si hay valores atípicos extremos se puede usar el argumento <code>coef = 3</code>.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb212-1" title="1"><span class="co"># Boxplot peso terneros con rango = 3</span></a>
<a class="sourceLine" id="cb212-2" title="2"><span class="kw">ggplot</span>(terneros, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="st">&quot;&quot;</span>, <span class="dt">y =</span> Peso)) <span class="op">+</span></a>
<a class="sourceLine" id="cb212-3" title="3"><span class="st">  </span><span class="kw">geom_boxplot</span>(<span class="dt">coef =</span> <span class="dv">3</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb212-4" title="4"><span class="st">  </span><span class="kw">coord_flip</span>()</a></code></pre></div>
<p><img src="intro-DOE-R_files/figure-html/unnamed-chunk-106-1.png" width="672" /></p>
<p>El valor <code>peso = 384</code> es un outlier extremo.</p>
</div>
<div id="medidas-de-forma" class="section level3">
<h3><span class="header-section-number">5.4.5</span> Medidas de forma</h3>
<p>Las medidas de forma resumen otros aspectos de la distribución como el sesgo o asimetría o la variabilidad en distribuciones unimodales o kurtosis.</p>
<p>La <strong>asimetría</strong> de una distribución hace referencia a como se distribuyen los valores en torno a la media.
En una distribución simétrica, la mitad izquierda es identica a la mitad derecha.</p>
<p><img src="intro-DOE-R_files/figure-html/unnamed-chunk-107-1.png" width="672" /></p>
<p>La <strong>kurtosis</strong> indica cuanto se concentran los valores en torno a la media. Las distribuciones leptocurticas tienen menor variabilidad. Lo opuesto ocurre con las platicurticas.</p>
<p><img src="intro-DOE-R_files/figure-html/unnamed-chunk-108-1.png" width="672" /></p>
<p>Hay varias formas de calcular los coeficientes de asimetría y kurtosis. Una de ellas deriva de los momentos estandarizados:</p>
<p><span class="math display">\[
m_k = \dfrac{\sum (X_i - \bar{X})^k}{n}
\]</span></p>
<p>Si <span class="math inline">\(k = 1\)</span>, <span class="math inline">\(m = 0\)</span> dado que <span class="math inline">\(\sum (X_i - \bar{X}) = 0\)</span>. En cambio, si <span class="math inline">\(k = 2\)</span>, <span class="math inline">\(m\)</span> es igual al estimador sesgado de la varianza poblacional. Así los momentos 3 y 4 tienen información sobre la asimetría y curtosis.</p>
<p>El coeficiente <span class="math inline">\(\sqrt{b_1}\)</span> indica la asimetría:</p>
<p><span class="math display">\[
\sqrt{b_1} = \dfrac{m_3}{\sqrt{m_2^3}} = \dfrac{\sqrt{n} \sum (X_i - \bar{X})^3}{\sqrt{ \left[ \sum(X_i - \bar{X})^2 \right]^3}}
\]</span></p>
<ul>
<li>Si <span class="math inline">\(\sqrt{b_1} = 0\)</span> la distribución es simétrica</li>
<li>Si <span class="math inline">\(\sqrt{b_1} &gt; 0\)</span> la distribución es sesgada a derecha</li>
<li>Si <span class="math inline">\(\sqrt{b_1} &lt; 0\)</span> la distribución es sesgada a izquierda</li>
</ul>
<p>El coeficiente <span class="math inline">\(b_2\)</span> indica la kurtosis</p>
<p><span class="math display">\[
b_2 = \dfrac{m_4}{m_2^2} = \dfrac{n \sum (X_i - \bar{X})^4}{\left[ \sum(X_i - \bar{X})^2 \right]^2}
\]</span></p>
<ul>
<li>Si <span class="math inline">\(b_2 = 3\)</span> la distribución es normal</li>
<li>Si <span class="math inline">\(b_2 &gt; 3\)</span> la distribución es leptocirtoca</li>
<li>Si <span class="math inline">\(b_2 &lt; 3\)</span> la distribución es platocurtica</li>
</ul>
<p>En <strong>R</strong> los coeficientes de kurtosis y asimetría se obtienen del as funciones <code>skewness()</code> y <code>kurtosis()</code> del paquete <code>moments</code>:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb213-1" title="1"><span class="kw">library</span>(moments)</a>
<a class="sourceLine" id="cb213-2" title="2"></a>
<a class="sourceLine" id="cb213-3" title="3"><span class="co"># asimetría</span></a>
<a class="sourceLine" id="cb213-4" title="4"><span class="kw">skewness</span>(terneros<span class="op">$</span>Peso)</a></code></pre></div>
<pre><code>## [1] 0.3905109</code></pre>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb215-1" title="1"><span class="co"># kurtosis</span></a>
<a class="sourceLine" id="cb215-2" title="2"><span class="kw">kurtosis</span>(terneros<span class="op">$</span>Peso)</a></code></pre></div>
<pre><code>## [1] 3.314532</code></pre>
</div>
<div id="todas-las-medidas-juntas" class="section level3">
<h3><span class="header-section-number">5.4.6</span> Todas las medidas juntas</h3>
<p>Usando la función <code>summarise()</code> de <code>dplyr</code> se pueden calcular una o más estadísticas de resumen y resumirlas en forma de tabla. Asímismo también pueden calcularse por subconjuntos.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb217-1" title="1"><span class="kw">library</span>(moments)</a>
<a class="sourceLine" id="cb217-2" title="2"></a>
<a class="sourceLine" id="cb217-3" title="3"><span class="co"># General</span></a>
<a class="sourceLine" id="cb217-4" title="4">terneros <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb217-5" title="5"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">n =</span> <span class="kw">length</span>(Peso), <span class="dt">media =</span> <span class="kw">mean</span>(Peso), <span class="dt">mediana =</span> <span class="kw">median</span>(Peso), <span class="dt">desv =</span> <span class="kw">sd</span>(Peso),</a>
<a class="sourceLine" id="cb217-6" title="6">            <span class="dt">min =</span> <span class="kw">min</span>(Peso), <span class="dt">max =</span> <span class="kw">max</span>(Peso), <span class="dt">IQR =</span> <span class="kw">IQR</span>(Peso), <span class="dt">Q20 =</span> <span class="kw">quantile</span>(Peso, <span class="fl">0.2</span>),</a>
<a class="sourceLine" id="cb217-7" title="7">            <span class="dt">Q80 =</span> <span class="kw">quantile</span>(Peso, <span class="fl">0.8</span>), <span class="dt">asim =</span> <span class="kw">skewness</span>(Peso), <span class="dt">kurt =</span> <span class="kw">kurtosis</span>(Peso))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 11
##       n media mediana  desv   min   max   IQR   Q20   Q80  asim  kurt
##   &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  1598  183.     180  37.2    78   384    48   152  213. 0.391  3.31</code></pre>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb219-1" title="1"><span class="co"># Estadítica de resumen por Procedencia</span></a>
<a class="sourceLine" id="cb219-2" title="2">terneros <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb219-3" title="3"><span class="st">  </span><span class="kw">group_by</span>(Procedencia) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb219-4" title="4"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">n =</span> <span class="kw">length</span>(Peso), <span class="dt">media =</span> <span class="kw">mean</span>(Peso), <span class="dt">mediana =</span> <span class="kw">median</span>(Peso), <span class="dt">desv =</span> <span class="kw">sd</span>(Peso),</a>
<a class="sourceLine" id="cb219-5" title="5">            <span class="dt">min =</span> <span class="kw">min</span>(Peso), <span class="dt">max =</span> <span class="kw">max</span>(Peso), <span class="dt">IQR =</span> <span class="kw">IQR</span>(Peso), <span class="dt">Q20 =</span> <span class="kw">quantile</span>(Peso, <span class="fl">0.2</span>),</a>
<a class="sourceLine" id="cb219-6" title="6">            <span class="dt">Q80 =</span> <span class="kw">quantile</span>(Peso, <span class="fl">0.8</span>), <span class="dt">asim =</span> <span class="kw">skewness</span>(Peso), <span class="dt">kurt =</span> <span class="kw">kurtosis</span>(Peso))</a></code></pre></div>
<pre><code>## # A tibble: 7 x 12
##   Procedencia     n media mediana  desv   min   max   IQR   Q20   Q80
##   &lt;chr&gt;       &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Don Alberto    69  179.     182  26.9   110   222    46  155.  205.
## 2 La Alameda    201  190.     182  39.5   122   294    52  156   226 
## 3 La Estrella   118  179.     180  14.2   144   218    18  168   188 
## 4 La Rosita      98  180.     180  17.4   140   242    22  166   192 
## 5 La Segunda     43  229.     228  24.8   180   288    31  210   247.
## 6 Las Glicin…   494  160.     155  33.7    78   280    44  130   186 
## 7 Los Corral…   575  197.     196  35.8    96   384    50  168   226 
## # ... with 2 more variables: asim &lt;dbl&gt;, kurt &lt;dbl&gt;</code></pre>
</div>
</div>
<div id="distribuciones-directamente-la-normal-y-tcl" class="section level2">
<h2><span class="header-section-number">5.5</span> distribuciones (directamente la normal y TCL)</h2>
</div>
<div id="ic" class="section level2">
<h2><span class="header-section-number">5.6</span> IC</h2>
</div>
<div id="test-hipotesis" class="section level2">
<h2><span class="header-section-number">5.7</span> Test hipotesis</h2>

</div>
</div>








            </section>

          </div>
        </div>
      </div>
<a href="introduccion-a-ggplot2.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"download": null,
"toc": {
"collapse": "subsection",
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
},
"search": true,
"highlight": "tango"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
